<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Secrets\Secrets.csproj" />
    <ProjectReference Include="..\..\Services\Customers\Customers.Infrastructure\Customers.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Services\Products\Products.Infrastructure\Products.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Services\Orders\Orders.Infrastructure\Orders.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Services\Inventory\Inventory.Service\Inventory.Service.csproj" />
    <ProjectReference Include="..\..\Services\Payments\Payments.Service\Payments.Service.csproj" />
  </ItemGroup>
</Project>
